# Gitleaks configuration file

title = "gitleaks config"

# Global settings
[extend]
# useDefault will extend the base configuration with the default gitleaks config:
# https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

[allowlist]
description = "global allow lists"
paths = [
    '''gitleaks.toml''',
    '''(.*?)(jpg|gif|doc|pdf|bin)$''',
    '''(go.mod|go.sum)$''',
]
regexes = [
    '''219-09-9999''', # Fake SSN
    '''078-05-1120''', # Fake SSN
    '''(9[0-9]{2}|666)-\d{2}-\d{4}''', # Fake SSN
]
stopwords = [
    '''potential''',
    '''secret''',
    '''REPLACEME''',
    '''example''',
    '''xxxxxxxx''',
    '''abcdefgh''',
    '''00000000''',
    '''11111111''',
    '''AAAAAAAA''',
    '''BBBBBBBB''',
    '''CCCCCCCC''',
    '''DDDDDDDD''',
]

# Additional custom rules for GitHub Actions security
[[rules]]
id = "github-actions-secret"
description = "GitHub Actions secret usage"
regex = '''\$\{\{\s*secrets\.[A-Z_]+\s*\}\}'''
keywords = [
    "secrets.",
]

[[rules]]
id = "hardcoded-token"
description = "Hardcoded token in GitHub Actions"
regex = '''(?i)(token|key|password|secret)[\s]*[:=][\s]*["\']?[a-zA-Z0-9]{20,}["\']?'''
keywords = [
    "token:",
    "key:",
    "password:",
    "secret:",
]
