# Basic Ruff configuration
target-version = "py39"

[lint]
select = ["E", "F", "W", "Q", "I", "N"]
ignore = ["E101", "E302", "I001"]

# Exclude common directories
exclude = [
    ".git",
    ".pixi",
    "__pycache__",
]